version: "3.3"

services:
  nginx:
    container_name: si_nginx
    image: nginx
    ports:
      - "8003:80"
    volumes:
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./backend:/var/www/app"
    depends_on:
      - "php-fpm"

  php-fpm:
    container_name: si_php
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - "./backend:/var/www/app"
    user: "1000:1000"
    depends_on:
      - "mysql"

  mysql:
    container_name: si_mysql
    image: mysql:8.0.26
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "fl_base"
      MYSQL_USER: "fl_admin"
      MYSQL_PASSWORD: "fl_admin"
    volumes:
      - "./tmp/mysql:/var/lib/mysql"
    user: "1000:1000"
